# Generated by Django 5.2.6 on 2025-09-29 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
    ]
